train: C:/Users/dengl/OneDrive/Dokumente/HTL/5. Klasse/ITP/Projekt/Assets/Annotated-Paper-Plastic/images/train
val: C:/Users/dengl/OneDrive/Dokumente/HTL/5. Klasse/ITP/Projekt/Assets/Annotated-Paper-Plastic/images/val

names:
  0: plastic
  1: paper
